name: FitBro
description: "A new Flutter project."

publish_to: "none" 



version: 1.0.0+3

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  loading_animation_widget: ^1.3.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.2
  flutter_svg: ^2.1.0
  lottie: ^3.3.1
  animated_splash_screen: ^1.3.0
  toastification: ^3.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  simple_circular_progress_bar: ^1.0.2
  smooth_page_indicator: ^1.2.1
  flutter_animate: ^4.5.2
  flutter_screenutil: ^5.9.3
  animate_do: ^4.2.0
  share_plus: ^11.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^19.1.0
  google_mobile_ads: ^6.0.0
  url_launcher: ^6.3.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1


flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/json/exercises.json
    - assets/json/meals.json
    - assets/Lottie/
